var rawCactusData = {
  "results": [{
    "listing_id": 120881959,
    "state": "active",
    "user_id": 10718414,
    "category_id": 69173669,
    "title": "Sculpture Sphere, Clay Ball Stamp, Giselle No. 5 Original, GIFT SET, Two Random, Handmade Texture",
    "description": "These sculpture balls are very fun to use. You simply roll them along the clay to produce a pattern or texture that is a little different every time. You can also hold one side of the ball and press the other side into the clay for a round stamped impression. I use no molds, so very single one I make is different. Each is its own little piece of unique artwork. Nobody in the world will have the same sculpture ball as you.\n\nThis listing is for two (2) randomly selected bisque sculpture balls, between 3\/4&quot; and 1 1\/4&quot; in diameter.\n\nI will select the patterns of your stamps at random, but I have added some choices to have a better idea of your taste before I choose for you. PLEASE NOTE: If you wish to select the exact pattern you will receive, you&#39;ll need to purchase one of the Choose Your Own listings found here: https:\/\/www.etsy.com\/shop\/GiselleNo5\/search?search_query=ball\n\nDEPTH OF DESIGN: \n1. Fine Detail - These designs will be shallower and more complex, good for use with stains and light glazes, jewelry making, fine texture.\n-OR-\n2. Deep and Clear - These designs are deep and clear, usually simpler. Best for use with larger pottery items and pooling glazes.\n-OR-\n3. Mix of Both - Often the designs I make are both deep enough for larger pottery items and finely detailed at the same time. \n\nPATTERN PREFERENCES: \n1. Organic Abstract - inspired by nature, this includes fluid lines and forms that resemble plants, flowers, and leaves\n2. Modern Abstract - inspired by architecture, this includes geometric shapes, angles, circles, modern lines and clean design\n3. Stars and Dots - self explanatory, I hope\n4. Spirals and Waves - again, hoping this is self-explanatory\n5. Surprise Me! - I will send you two stamps completely at random. It&#39;s like Russian Roulette, only much safer.\n\nIf you have any questions after reading this listing, please feel free to contact me at any time.\n\nIMPORTANT: By purchasing this listing you agree to the terms of the listing and all shop policies, so please read the full listing and my policies before you buy. \n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nSTAMP CARE (all stamps): Keep clean with warm water, mild soap, and a soft brush like an old toothbrush. Clean and rinse between uses and allow to dry thoroughly before the next use. \n\nIMPORTANT: Please purchase separate stamps to use on food and for work with clay. \n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nSHORTBREAD DOUGH, FONDANT, AND OTHER FOODS:\nPlease see my other shop, GiselleNo5Handmade.etsy.com for cookie stamps.\n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nPOLYMER CLAY? Use:\n&gt; Bisque Stamps\n&gt; Polymer Clay Stamps\nIf the clay sticks to the stamp, either dust with baby powder before stamping or allow the clay to cool before continuing work. \n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nSTONEWARE CLAY, EARTHENWARE CLAY, or PORCELAIN CLAY? Use: \n&gt; Bisque Stamps\n&gt; Polymer Clay Stamps\nIf sticking occurs, either lightly dust the stamp with corn starch or lightly oil with olive oil or any other vegetable oil. \n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nPRECIOUS METAL CLAY? Use:\n&gt; Polymer Clay Stamps\nIf sticking occurs, lightly oil the stamp. I&#39;ve heard that spray cooking oil works nicely for this purpose. \n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nAIR DRY CLAY, PLAY-DOH, PAPER CLAY? Use: \n&gt; Polymer Clay Stamps\n&gt; Bisque Stamps\nIf sticking occurs, use corn starch or baby powder to lightly dust the stamp before each use. \n\nThe dye in Play-Doh will almost certainly stain the stamps, but it will not damage them or affect your future projects as long as you clean the stamps between each use. \n\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n\nCOPYRIGHT NOTICE: All designs, creative content, descriptions and images are copyright 2012-2015 by Giselle No. 5 - Giselle Massey - whether registered or unregistered. Though my stamps may be used as a tool to create a design on an item that will be sold, I do not permit them to be used to mass manufacture items in factory style production, and making copies of my stamps is strictly prohibited. Violation of this copyright may subject the violator to civil and\/or criminal prosecution. All rights reserved.",
    "creation_tsz": 1421958710,
    "ending_tsz": 1432323110,
    "original_creation_tsz": 1358524979,
    "last_modified_tsz": 1421958710,
    "price": "19.50",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["hand carved", "blush pink", "round ball", "dark black", "pattern and texture", "navy blue and teal", "desert cactus", "stars and spirals", "jewelry making", "DIY crafts", "giselleno5", "sculpture ball", "roller stamp"],
    "category_path": ["Supplies", "Handmade", "Tool"],
    "category_path_ids": [69150433, 69151267, 69173669],
    "materials": ["pottery", "pottery clay", "ceramic", "ceramic clay", "bisque", "earthenware", "stoneware", "Moroccan Sand"],
    "shop_section_id": 14625750,
    "featured_rank": null,
    "state_tsz": 1421856243,
    "url": "https:\/\/www.etsy.com\/listing\/120881959\/sculpture-sphere-clay-ball-stamp-giselle?utm_source=explorer&utm_medium=api&utm_campaign=api",
    "views": 3194,
    "num_favorers": 381,
    "shipping_template_id": 114418581,
    "processing_min": 10,
    "processing_max": 15,
    "who_made": "i_did",
    "is_supply": "true",
    "when_made": "2010_2015",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": ["Primitive", "Southwestern"],
    "non_taxable": false,
    "is_customizable": false,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": true,
    "used_manufacturer": false,
    "Images": [{
      "listing_image_id": 420309508,
      "hex_code": "6A655D",
      "red": 106,
      "green": 101,
      "blue": 93,
      "hue": 37,
      "saturation": 12,
      "brightness": 41,
      "is_black_and_white": false,
      "creation_tsz": 1359164841,
      "listing_id": 120881959,
      "rank": 1,
      "url_75x75": "https:\/\/img0.etsystatic.com\/011\/0\/6010929\/il_75x75.420309508_r1jr.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/011\/0\/6010929\/il_170x135.420309508_r1jr.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/011\/0\/6010929\/il_570xN.420309508_r1jr.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/011\/0\/6010929\/il_fullxfull.420309508_r1jr.jpg",
      "full_height": 1427,
      "full_width": 1500
    }, {
      "listing_image_id": 444498452,
      "hex_code": "B6ACA2",
      "red": 182,
      "green": 172,
      "blue": 162,
      "hue": 30,
      "saturation": 10,
      "brightness": 71,
      "is_black_and_white": false,
      "creation_tsz": 1364887275,
      "listing_id": 120881959,
      "rank": 2,
      "url_75x75": "https:\/\/img0.etsystatic.com\/011\/0\/6010929\/il_75x75.444498452_t8ej.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/011\/0\/6010929\/il_170x135.444498452_t8ej.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/011\/0\/6010929\/il_570xN.444498452_t8ej.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/011\/0\/6010929\/il_fullxfull.444498452_t8ej.jpg",
      "full_height": 1000,
      "full_width": 1500
    }, {
      "listing_image_id": 417405788,
      "hex_code": "C0AD97",
      "red": 192,
      "green": 173,
      "blue": 151,
      "hue": 32,
      "saturation": 21,
      "brightness": 75,
      "is_black_and_white": false,
      "creation_tsz": 1358524979,
      "listing_id": 120881959,
      "rank": 3,
      "url_75x75": "https:\/\/img0.etsystatic.com\/015\/0\/6010929\/il_75x75.417405788_leua.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/015\/0\/6010929\/il_170x135.417405788_leua.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/015\/0\/6010929\/il_570xN.417405788_leua.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/015\/0\/6010929\/il_fullxfull.417405788_leua.jpg",
      "full_height": 1098,
      "full_width": 1500
    }, {
      "listing_image_id": 420308570,
      "hex_code": "B29D89",
      "red": 178,
      "green": 157,
      "blue": 137,
      "hue": 29,
      "saturation": 23,
      "brightness": 69,
      "is_black_and_white": false,
      "creation_tsz": 1359164841,
      "listing_id": 120881959,
      "rank": 4,
      "url_75x75": "https:\/\/img0.etsystatic.com\/014\/0\/6010929\/il_75x75.420308570_q9cq.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/014\/0\/6010929\/il_170x135.420308570_q9cq.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/014\/0\/6010929\/il_570xN.420308570_q9cq.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/014\/0\/6010929\/il_fullxfull.420308570_q9cq.jpg",
      "full_height": 1000,
      "full_width": 1500
    }, {
      "listing_image_id": 657249220,
      "hex_code": "B0B6B5",
      "red": 176,
      "green": 182,
      "blue": 181,
      "hue": 170,
      "saturation": 3,
      "brightness": 71,
      "is_black_and_white": false,
      "creation_tsz": 1411433616,
      "listing_id": 120881959,
      "rank": 5,
      "url_75x75": "https:\/\/img0.etsystatic.com\/035\/0\/6010929\/il_75x75.657249220_dxid.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/035\/0\/6010929\/il_170x135.657249220_dxid.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/035\/0\/6010929\/il_570xN.657249220_dxid.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/035\/0\/6010929\/il_fullxfull.657249220_dxid.jpg",
      "full_height": 403,
      "full_width": 403
    }],
    "Shop": {
      "shop_id": 6010929,
      "shop_name": "GiselleNo5",
      "user_id": 10718414,
      "creation_tsz": 1283884092,
      "title": "handcrafted . original . unique . stamps for clay",
      "announcement": "For step-by-step instructions on using Etsy gift cards, please see this article: https:\/\/www.etsy.com\/help\/article\/5465?ref=help_search_result#Q1\r\n\r\nWelcome to Giselle No. 5! I sell a wide variety of handmade clay stamps for texturing pottery and polymer clay. Everything in my shop is designed, made, photographed, marketed, and shipped by me from my home in California. I personally design and make ALL my stamps by hand from polymer or ceramic clay. The only time my stamps are out of my hands is when I drop them off at a local pottery studio to be fired in their kiln. \r\n\r\nI know that clay stamps aren&#39;t for everybody. That&#39;s okay, I make pottery too! Check out my new shop, GiselleNo5Handmade.etsy.com. I have lots of stuff from beads and magnets to dinnerware and bakeware that I hand-cast in vintage molds and decorate with intricate designs.\r\n\r\nNEW TO ETSY? First time shoppers can get $5 off their first purchase with this link!: etsy.me\/1oN9utZ\r\n\r\nLOCAL CUSTOMERS: Use coupon code LOCALPICKUP if you&#39;d like to pick up your stamps directly from me. I love to meet local artists, and I promise I don&#39;t bite! \r\n\r\nPLEASE check the processing times on each listing before you place your order. If you&#39;re concerned about receiving an order by a specific date, please contact me.\r\n\r\nLIKE my Facebook page to see new designs before they&#39;re available in my shop. https:\/\/www.facebook.com\/GiselleNo5\r\n\r\nPlease feel free to send me a convo: http:\/\/www.etsy.com\/conversations\/new?with_id=10718414\r\n\r\n*********************************************************************************************\r\n\r\nANSWERS TO FAQs and INFORMATION ON CUSTOM ORDERS: https:\/\/www.etsy.com\/shop\/GiselleNo5\/policy\r\n\r\n*********************************************************************************************\r\n\r\nhttps:\/\/www.facebook.com\/GiselleNo5\r\n\r\nhttp:\/\/www.pinterest.com\/GiselleNo5\/etsy-my-treasuries\/\r\n\r\nhttp:\/\/www.pinterest.com\/GiselleNo5\/etsy-delicious-treasuries\/\r\n\r\nGiselleNo5Handmade.etsy.com\r\n\r\n*********************************************************************************************\r\n",
      "currency_code": "USD",
      "is_vacation": false,
      "vacation_message": "I&#39;m on vacation till further notice! All existing orders will ship on schedule and I will be checking my messages and email. Please feel free to contact me while I&#39;m away! ",
      "sale_message": "Hello! \r\n\r\nThank you so much for your order and thank you for buying handmade! \r\n\r\nPlease allow **up to four weeks** for your order to be made and shipped out unless the listing specifies a shorter processing time. If you&#39;d like a more specific date, feel free to ask. I know when I order something online I can&#39;t wait to get it! \r\n\r\nSee shop policies for FAQs: https:\/\/www.etsy.com\/shop\/GiselleNo5\/policy\r\n\r\nI will send an email notification with tracking info within the US and delivery confirmation everywhere when I ship your order.  \r\n\r\nPlease note: If you have placed separate orders close together, I will ship them in the same package unless you specify otherwise or they are going to separate addresses. If this is going to cause a problem with International Customs, please let me know.\r\n\r\nThanks, \r\nGiselle\r\n\r\nhttps:\/\/www.facebook.com\/GiselleNo5\r\nhttp:\/\/www.pinterest.com\/GiselleNo5\/clay-stamps\/\r\nGiselleNo5Handmade.etsy.com",
      "digital_sale_message": null,
      "last_updated_tsz": 1418398042,
      "listing_active_count": 154,
      "login_name": "GiselleNo5",
      "accepts_custom_requests": false,
      "policy_welcome": "Welcome and thank you for visiting Giselle No. 5! \r\n\r\nAll my items are handcrafted one at a time by me in my original designs. So there are variations in size and slight differences in each reproduction of a specific stamp design. \r\n\r\nPlease feel free to contact me with questions and suggestions. If you are looking for a stamp but don&#39;t see one in my shop, feel free to ask about it. Please read all my shop policies before purchasing!\r\n\r\nMETAL CLAY CUSTOMERS, PARENTS, and BAKERS: If you want a stamp in a material that does not appear on the listing, just ask! I will usually make the design in polymer clay for use by children or PMC artists at no extra charge. Exceptions to this are very rare. I can make many of my designs high-fired for use with food by special request. These are considered a custom order so please contact me to work out the details and cost so I can create a reserved listing just for you. I check my Etsy account obsessively .... ahem .... conscientiously through the day and respond promptly to customers.\r\n\r\nI hope you like my creations! \r\n",
      "policy_payment": "I accept PayPal, Etsy gift cards and direct checkout. With all forms of payment, the item will ship only after payment clears. I collect sales tax only for fellow California residents. All other customers are responsible for any applicable local or state sales tax, import tax, and customs fees.\r\n\r\nCANCELLATIONS AND RETURNS: For a full refund including shipping you must cancel your order BEFORE I begin work on any made-to-order items. Once an order has shipped, you must ship it back to me in its original condition at your own expense for a refund of the item price minus shipping charges. See below for special notes on refunds of custom-made items or special requests. \r\n\r\nALL RETURNS, PLEASE NOTE: \r\nIf you wish to return an item, please be available to communicate via Etsy account or email until we agree on a resolution. I honestly want my customers to be happy, so when you approach me please keep in mind that I will work with you and treat you with kindness and respect. Please do the same when you contact me.\r\n\r\nIF YOU RECEIVE THE WRONG ITEM, and it is MY mistake, I will promptly send you a prepaid shipping label to return the item to me. Upon receipt of the item in its original condition, I will send out a replacement as soon as possible, also at my own expense. \r\n\r\nIF YOU RECEIVE THE WRONG ITEM BECAUSE YOU DID NOT READ THE LISTING FULLY, I am not responsible for return shipping charges. You must return the item to me in its original condition at your own expense. I will bill you for the return shipping and send out a replacement as soon as I can after receiving payment. The exception to this is special custom stamps like the maker&#39;s mark signature stamp. Please see the shop policies regarding that category of stamps.\r\n\r\nRETURNS FROM EU: If you receive the wrong item, see the policies above. If you simply change your mind about your purchase within the 14-day window after receipt, you are welcome to send back your item at your own expense and in the original condition for a refund of the item cost. I do not refund shipping charges or reimburse for shipping on international orders. No refunds or exchanges on custom-made items like signature stamps. \r\n\r\nUSING COUPON CODES: It is the responsibility of the customer to enter any coupon codes correctly at the time of purchase to receive a discount. \r\n\r\nGIFT CARD HELP: https:\/\/www.etsy.com\/help\/article\/3088\r\n\r\n**NO TRADES**",
      "policy_shipping": "All orders ship by USPS First Class Mail for domestic orders and First Class International for any orders outside the US. I will send an email notification when your order ships with your ship date and a tracking number. This provides tracking within the US and delivery confirmation everywhere in the world. The notification and tracking number will be sent to the email associated with your Etsy account.  \r\n\r\nINTERNATIONAL CUSTOMS: Customer is solely responsible for paying any customs fees and\/or any additional fees or taxes incurred on international shipping. I ship First Class International. PLEASE REMEMBER that you must allow 2-5 weeks for the item to clear customs and reach your home or business.  \r\n\r\nCOMBINED INTERNATIONAL SHIPPING: If you are placing an international order of five or more listings, please let me know before you order and I&#39;ll be happy to combine your order into one custom listing, with a special shipping price. When you message me, please let me know all the items you want to order and what country it will be shipping to so I can give you an accurate estimate. \r\n\r\nLOST OR MISSING INTERNATIONAL ORDERS: I am not responsible for refunding or re-making lost or missing international orders. To protect my customers, I purchase insurance on all international orders over $50. If your order has gone astray, please contact me on Etsy or by email and I will work together with you to track down the package. \r\n\r\nINTERNATIONAL SHIPPING UPGRADES: If you want an upgrade to Priority Express International 3-5 days shipping, please let me know and I will create a custom listing for you with the shipping upgrade and insurance added. ",
      "policy_refunds": "SPECIAL REQUESTS and HIGH-FIRED STAMPS are considered custom orders and are nonrefundable from the time work begins on the item.\r\n\r\nORDERS RECEIVED DAMAGED OR BROKEN: If you receive your order in a damaged condition, please take a photograph of the damaged item(s) and send it to me right away so I can report the damage to the USPS. I will be more than happy to replace the item at no additional cost to you.\r\n\r\nORDER CANCELLATIONS: If you make an order, then cancel it, you will receive a full refund UNLESS the item has already been made and shipped, in which case you must ship it back to me at your own expense for a refund of the item price minus shipping costs. Custom orders are nonrefundable (see above). \r\n\r\nINCORRECT ORDERS: If I have made a mistake (missing item, wrong stamp, etc.) please send me a message here on Etsy for a prompt reply and my full attention to resolve the issue to your satisfaction at no extra cost to you. \r\n\r\nCUSTOMER SATISFACTION: If you are unhappy with your stamps or have any questions as to their use, please don&#39;t hesitate to send me a message for a prompt reply. I&#39;ve done lots of experimenting with my stamps so I am happy to offer glaze suggestions along with any other help I can. ",
      "policy_additional": "CUSTOM STAMP ORDERS: Please understand that custom or personalized orders are non-refundable once work has started on the item or items. \r\n\r\nAll of my stamps are handmade, not machine made, so while I am willing to work from inspiration photos to create a unique design, I do not make direct copies of other people&#39;s work or clipart images. The exception to this is if a customer sends me a digital file of their initials for a signature stamp.\r\n\r\nCUSTOM STAMP FEES: For a custom made stamp of a business name, logo, or your initials to sign your pottery, I charge a $25 custom design fee. This is in addition to the actual cost of the stamp and shipping charges. If the design is particularly complex, I reserve the right to charge a higher custom design fee and sole use fee at my discretion. You will be given a final quote before your purchase.\r\n\r\nCUSTOM DESIGN OWNERSHIP: All stamp designs are the intellectual property of Giselle No. 5. If I create a stamp at your request, that same design may later be sold in my shop, with the exception of business logos. If you want a stamp made for your sole use, please make that clear when you&#39;re requesting the item. In addition, be aware that  a photo of your custom item may be used as an example of a custom stamp I&#39;ve made in the past so that I can sell custom items to other customers. \r\n\r\nONE-OF-A-KIND AND UNIQUE STAMPS: Since every one of my stamps is handmade and one of a kind, when you place an order you will receive that stamp design but likely not the exact item pictured here on Etsy. The exception to this is if the listing specifies that the exact stamp pictured is for sale, in which case you will receive the exact stamp pictured. Please convo me with any questions.\r\n\r\nRANDOM STAMPS OR SETS OF STAMPS: These stamps are selected and shipped at random and are not necessarily the same as shown in the listing photos. I make each design one at a time by hand, so they are all different. You can see a good number of examples of past designs in the listing photos. If you wish to choose from the stamps I have in stock, please purchase one of the CHOOSE YOUR OWN sets in my shop, or ask me to make a listing just for you.\r\n\r\nPROCESSING TIME FOR ORDERS: Current turnaround on all orders is 3-4 weeks unless otherwise noted in the listing. \r\n\r\nFIRING SCHEDULE: I bake all my polymer clay stamps in my own oven, but for bisque or high-fire I use a local pottery studio. How often my stamps are fired depends on how busy the potter is. For stamps in bisque, please remember that while I do my best to keep popular designs in stock so that I can ship out orders sooner, if the items are made to order I have to allow time to make, dry, and fire them before shipping. \r\n\r\n",
      "policy_seller_info": null,
      "policy_updated_tsz": 1421904553,
      "vacation_autoreply": "Thanks for your interest in my shop! \r\n\r\nI&#39;m on vacation till further notice. All existing orders will ship on schedule and I will be checking my messages and email. Please feel free to contact me while I&#39;m away! \r\n\r\nGiselle ",
      "url": "https:\/\/www.etsy.com\/shop\/GiselleNo5?utm_source=explorer&utm_medium=api&utm_campaign=api",
      "image_url_760x100": "https:\/\/img1.etsystatic.com\/049\/0\/6010929\/iusb_760x100.14570185_pgw2.jpg",
      "num_favorers": 5422,
      "languages": ["en-US"],
      "upcoming_local_event_id": null
    }
  }, {
    "listing_id": 219592654,
    "state": "active",
    "user_id": 6846562,
    "category_id": 69176399,
    "title": "Carolina - Small Hanging Globe Terrarium Succulent Arrangement w. display stand!",
    "description": "A succulent arrangement made up of 3 succulents arranged in a cute 4&#39;&#39; glass orb that can sit on a table or be hung with string or wire. \nThis includes the stand pictured, but if you don&#39;t want it or would rather hand it let me know! (It will save money on shipping. )\n\nYou get the exact one pictured. (If you want a custom one, please \n\nCarefully packaged and shipped to ensure safe delivery. C: \n\nWill include basic care instructions.\n\nMakes a cute gift! I also have larger orbs which can be connected with this and hung in groups. \n\nMessage me with any questions or concerns!  \n\nIf you live outside of the U.S., message me and I can give you accurate shipping rates! ",
    "creation_tsz": 1421958484,
    "ending_tsz": 1432322884,
    "original_creation_tsz": 1421958484,
    "last_modified_tsz": 1421958757,
    "price": "25.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["ooak", "succulent", "plant", "desert", "terrarium", "succulents", "moss", "glass", "garden", "flowers", "cactus", "natural", "arrangement"],
    "category_path": ["Plants and Edibles", "Plant", "Terrarium"],
    "category_path_ids": [68887346, 69153219, 69176399],
    "materials": ["ceramic mushroom", "reindeer moss", "sphagnum moss", "rocks", "jar", "glass", "moss", "succulent", "pebbles", "soil", "activated charcoal", "gravel", "Carbon"],
    "shop_section_id": 16278529,
    "featured_rank": null,
    "state_tsz": 1421958484,
    "url": "https:\/\/www.etsy.com\/listing\/219592654\/carolina-small-hanging-globe-terrarium?utm_source=explorer&utm_medium=api&utm_campaign=api",
    "views": 0,
    "num_favorers": 0,
    "shipping_template_id": 6794990730,
    "processing_min": 3,
    "processing_max": 5,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2015",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": false,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false,
    "Images": [{
      "listing_image_id": 715896987,
      "hex_code": "63412C",
      "red": 99,
      "green": 65,
      "blue": 44,
      "hue": 23,
      "saturation": 55,
      "brightness": 38,
      "is_black_and_white": false,
      "creation_tsz": 1421958757,
      "listing_id": 219592654,
      "rank": 1,
      "url_75x75": "https:\/\/img1.etsystatic.com\/058\/0\/9775684\/il_75x75.715896987_kmko.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/058\/0\/9775684\/il_170x135.715896987_kmko.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/058\/0\/9775684\/il_570xN.715896987_kmko.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/058\/0\/9775684\/il_fullxfull.715896987_kmko.jpg",
      "full_height": 1136,
      "full_width": 852
    }, {
      "listing_image_id": 715768210,
      "hex_code": "645E53",
      "red": 100,
      "green": 94,
      "blue": 83,
      "hue": 39,
      "saturation": 17,
      "brightness": 39,
      "is_black_and_white": false,
      "creation_tsz": 1421958484,
      "listing_id": 219592654,
      "rank": 2,
      "url_75x75": "https:\/\/img0.etsystatic.com\/054\/0\/9775684\/il_75x75.715768210_mips.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/054\/0\/9775684\/il_170x135.715768210_mips.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/054\/0\/9775684\/il_570xN.715768210_mips.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/054\/0\/9775684\/il_fullxfull.715768210_mips.jpg",
      "full_height": 1136,
      "full_width": 852
    }, {
      "listing_image_id": 715896995,
      "hex_code": "5E4F42",
      "red": 94,
      "green": 79,
      "blue": 66,
      "hue": 28,
      "saturation": 29,
      "brightness": 36,
      "is_black_and_white": false,
      "creation_tsz": 1421958757,
      "listing_id": 219592654,
      "rank": 3,
      "url_75x75": "https:\/\/img1.etsystatic.com\/046\/0\/9775684\/il_75x75.715896995_h0dg.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/046\/0\/9775684\/il_170x135.715896995_h0dg.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/046\/0\/9775684\/il_570xN.715896995_h0dg.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/046\/0\/9775684\/il_fullxfull.715896995_h0dg.jpg",
      "full_height": 1500,
      "full_width": 1125
    }, {
      "listing_image_id": 715891431,
      "hex_code": "7F7B74",
      "red": 127,
      "green": 123,
      "blue": 116,
      "hue": 38,
      "saturation": 8,
      "brightness": 49,
      "is_black_and_white": false,
      "creation_tsz": 1421958484,
      "listing_id": 219592654,
      "rank": 4,
      "url_75x75": "https:\/\/img1.etsystatic.com\/048\/0\/9775684\/il_75x75.715891431_qqnp.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/048\/0\/9775684\/il_170x135.715891431_qqnp.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/048\/0\/9775684\/il_570xN.715891431_qqnp.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/048\/0\/9775684\/il_fullxfull.715891431_qqnp.jpg",
      "full_height": 1500,
      "full_width": 1125
    }, {
      "listing_image_id": 715768230,
      "hex_code": "867F7A",
      "red": 134,
      "green": 127,
      "blue": 122,
      "hue": 25,
      "saturation": 8,
      "brightness": 52,
      "is_black_and_white": false,
      "creation_tsz": 1421958484,
      "listing_id": 219592654,
      "rank": 5,
      "url_75x75": "https:\/\/img0.etsystatic.com\/048\/0\/9775684\/il_75x75.715768230_se2e.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/048\/0\/9775684\/il_170x135.715768230_se2e.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/048\/0\/9775684\/il_570xN.715768230_se2e.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/048\/0\/9775684\/il_fullxfull.715768230_se2e.jpg",
      "full_height": 1500,
      "full_width": 1125
    }],
    "Shop": {
      "shop_id": 9775684,
      "shop_name": "AllieCatsTrinkets",
      "user_id": 6846562,
      "creation_tsz": 1406063428,
      "title": null,
      "announcement": "Hello! I will be listing new Terrariums this week. My cat decided to knock down a handful of my terrariums and now I have to recreate and try to salvage what can be recovered from the wreckage. \n\nKeep an eye out! Thank you for looking!\n\nKeep in mind I can still make custom orders! C: ",
      "currency_code": "USD",
      "is_vacation": false,
      "vacation_message": null,
      "sale_message": null,
      "digital_sale_message": null,
      "last_updated_tsz": 1417384878,
      "listing_active_count": 9,
      "login_name": "Madefrcupcakeicing",
      "accepts_custom_requests": false,
      "policy_welcome": null,
      "policy_payment": null,
      "policy_shipping": null,
      "policy_refunds": null,
      "policy_additional": null,
      "policy_seller_info": null,
      "policy_updated_tsz": 1418658394,
      "vacation_autoreply": null,
      "url": "https:\/\/www.etsy.com\/shop\/AllieCatsTrinkets?utm_source=explorer&utm_medium=api&utm_campaign=api",
      "image_url_760x100": "https:\/\/img0.etsystatic.com\/056\/0\/9775684\/iusb_760x100.14614518_maj5.jpg",
      "num_favorers": 15,
      "languages": ["en-US"],
      "upcoming_local_event_id": null
    }
  }, {
    "listing_id": 188986935,
    "state": "active",
    "user_id": 28415352,
    "category_id": 69160487,
    "title": "PIF RAK Silver Plated Pendant and Necklace - Kawaii Cactus Boo Boo w\/ Beads and Charms",
    "description": "THE PRODUCT:\r\nYou are seconds from owning one cutesty cactus charm necklace.\r\n\n***THIS IS A PAY IT FORWARD\/RANDOM ACTS OF KINDNESS LISTING. THE ITEM IS PRACTICALLY FREE. YOU JUST PAY FOR SHIPPING\/HANDLING***\n\r\nBut, oh no, he&#039;s hurt!!  Can you help?\r\n\r\nThis necklace was made from kawaii artwork, beads and charms.\r\n\r\nArtwork was set in the pendant by epoxy.\r\n\r\nI embellished the bead-chain necklace with several charms and beads.\r\n\r\nNecklace closes with a lobster clasp.\r\n\r\nPendant is 1&quot; diameter.  Total necklace measures 10&quot; from the neck.\r\n\r\nThis was made with loving care and from a smoke-free household. I am always looking for other pattern\/design ideas, so feel free to give me suggestions or requests.\r\n\r\nYour purchase will be delivered in an organza bag, ready for gift-giving!\r\n\r\nSHIPPING AND HANDLING:\r\nDomestic (US and US territories): $3.00\r\nCanada\/Mexico: $7.00\r\nAll Others: $8.00\r\n\r\nThank you for browsing my store!",
    "creation_tsz": 1421958022,
    "ending_tsz": 1432322422,
    "original_creation_tsz": 1399587736,
    "last_modified_tsz": 1421958022,
    "price": "0.99",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["jewelry", "art", "tween", "girl", "western", "cowgirl", "desert", "plant", "band aid", "sick", "nurture", "get well", "cute"],
    "category_path": ["Jewelry", "Necklace", "Beaded"],
    "category_path_ids": [68887482, 69151567, 69160487],
    "materials": ["love", "metal", "cardstock", "epoxy", "craft adhesive", "metal beads", "charms", "artisan beads"],
    "shop_section_id": 13813909,
    "featured_rank": null,
    "state_tsz": 1421509833,
    "url": "https:\/\/www.etsy.com\/listing\/188986935\/pif-rak-silver-plated-pendant-and?utm_source=explorer&utm_medium=api&utm_campaign=api",
    "views": 18,
    "num_favorers": 3,
    "shipping_template_id": null,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2015",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": ["Kawaii"],
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false,
    "Images": [{
      "listing_image_id": 600079948,
      "hex_code": "ACACAE",
      "red": 172,
      "green": 172,
      "blue": 174,
      "hue": 240,
      "saturation": 1,
      "brightness": 68,
      "is_black_and_white": false,
      "creation_tsz": 1399587736,
      "listing_id": 188986935,
      "rank": 1,
      "url_75x75": "https:\/\/img0.etsystatic.com\/039\/0\/7618100\/il_75x75.600079948_sje1.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/039\/0\/7618100\/il_170x135.600079948_sje1.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/039\/0\/7618100\/il_570xN.600079948_sje1.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/039\/0\/7618100\/il_fullxfull.600079948_sje1.jpg",
      "full_height": 560,
      "full_width": 687
    }, {
      "listing_image_id": 600183811,
      "hex_code": "9FA39D",
      "red": 159,
      "green": 163,
      "blue": 157,
      "hue": 100,
      "saturation": 3,
      "brightness": 63,
      "is_black_and_white": false,
      "creation_tsz": 1399587736,
      "listing_id": 188986935,
      "rank": 2,
      "url_75x75": "https:\/\/img1.etsystatic.com\/030\/0\/7618100\/il_75x75.600183811_ihgp.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/030\/0\/7618100\/il_170x135.600183811_ihgp.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/030\/0\/7618100\/il_570xN.600183811_ihgp.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/030\/0\/7618100\/il_fullxfull.600183811_ihgp.jpg",
      "full_height": 558,
      "full_width": 691
    }, {
      "listing_image_id": 600079924,
      "hex_code": "B8B9BA",
      "red": 184,
      "green": 185,
      "blue": 186,
      "hue": 210,
      "saturation": 1,
      "brightness": 72,
      "is_black_and_white": false,
      "creation_tsz": 1399587736,
      "listing_id": 188986935,
      "rank": 3,
      "url_75x75": "https:\/\/img0.etsystatic.com\/027\/0\/7618100\/il_75x75.600079924_f4mr.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/027\/0\/7618100\/il_170x135.600079924_f4mr.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/027\/0\/7618100\/il_570xN.600079924_f4mr.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/027\/0\/7618100\/il_fullxfull.600079924_f4mr.jpg",
      "full_height": 498,
      "full_width": 719
    }],
    "Shop": {
      "shop_id": 7618100,
      "shop_name": "JCristinasCreations",
      "user_id": 28415352,
      "creation_tsz": 1356815909,
      "title": "A menagerie of jewelry and findings.",
      "announcement": null,
      "currency_code": "USD",
      "is_vacation": false,
      "vacation_message": null,
      "sale_message": null,
      "digital_sale_message": "Once payment is received, you will receive an instant download for your purchase. account.  If you want it sent to another email address, please say so in your order and I can do that as well.  The collage is in JPG format.  If you need another format, please let me know and I will convert for you.",
      "last_updated_tsz": 1421866738,
      "listing_active_count": 550,
      "login_name": "jcristinascreations",
      "accepts_custom_requests": true,
      "policy_welcome": "I am a 37 year old mother of a wonderful 4 year old boy who is the light of my life. \nI started out sewing and sold baby items for about 8 years on Ebay and Etsy.\nI just recently became interested in jewelry, making it and selling findings. \nCheck out my items. There is always something new!",
      "policy_payment": "I accept PAYPAL.  \r\nI expect to receive payment within 7 days of the auction&#039;s end.",
      "policy_shipping": "I combine S&amp;H on multiple purchases.  See my listings for specifics on S&amp;H. \r\nI use USPS First Class and Priority Mail.\r\nI am not responsible for lost packages though, so please make sure you put insurance on your packages!",
      "policy_refunds": "I will accept returns if the mistake was mine (wrong item was sent, discrepancy in the listing).  If item is returned and it is not my mistake, you are responsible for returning shipping cost and it will not be refunded upon.  Your original item cost will be refunded.",
      "policy_additional": "I accept custom orders.  Just convo me and I will see what I can do!",
      "policy_seller_info": null,
      "policy_updated_tsz": 1418263074,
      "vacation_autoreply": null,
      "url": "https:\/\/www.etsy.com\/shop\/JCristinasCreations?utm_source=explorer&utm_medium=api&utm_campaign=api",
      "image_url_760x100": "https:\/\/img1.etsystatic.com\/051\/0\/7618100\/iusb_760x100.14467213_i3ym.jpg",
      "num_favorers": 147,
      "languages": ["en-US"],
      "upcoming_local_event_id": null
    }
  }, {
    "listing_id": 218920194,
    "state": "active",
    "user_id": 8504030,
    "category_id": 68887612,
    "title": "Batik Desert Sunset",
    "description": "A beautiful quilt using Batik fabrics in a southwestern pattern called Sky Lantern.Rich colors of turquoise,aqua,golds,blues,greens,bronze and reds.The background is sand colored.\r\nMachine quilted in a southwestern pattern .The backing is a water colored batik in rainbow colors.\r\nQueen size.  78&quot;x 88&quot;",
    "creation_tsz": 1421957778,
    "ending_tsz": 1432322178,
    "original_creation_tsz": 1421537618,
    "last_modified_tsz": 1421957778,
    "price": "300.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["Southwestern", "Sunset", "Desert", "Turquoise", "Cactus", "Kokopelli", "Gold", "Queen bed", "Masculine", "Batik", "Sky lantern", "Wall hanging", "Indian"],
    "category_path": ["Quilts", "Geometric"],
    "category_path_ids": [68887502, 68887612],
    "materials": ["All Cotton", "Batik Fabrics", "Polyester batting"],
    "shop_section_id": null,
    "featured_rank": 3,
    "state_tsz": 1421537618,
    "url": "https:\/\/www.etsy.com\/listing\/218920194\/batik-desert-sunset?utm_source=explorer&utm_medium=api&utm_campaign=api",
    "views": 7,
    "num_favorers": 1,
    "shipping_template_id": 631468140,
    "processing_min": 1,
    "processing_max": 2,
    "who_made": "i_did",
    "is_supply": "false",
    "when_made": "2010_2015",
    "is_private": false,
    "recipient": "unisex_adults",
    "occasion": null,
    "style": ["Southwestern"],
    "non_taxable": false,
    "is_customizable": false,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false,
    "Images": [{
      "listing_image_id": 713324809,
      "hex_code": "B5915E",
      "red": 181,
      "green": 145,
      "blue": 94,
      "hue": 35,
      "saturation": 48,
      "brightness": 70,
      "is_black_and_white": false,
      "creation_tsz": 1421537618,
      "listing_id": 218920194,
      "rank": 1,
      "url_75x75": "https:\/\/img1.etsystatic.com\/049\/0\/5713595\/il_75x75.713324809_m2pq.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/049\/0\/5713595\/il_170x135.713324809_m2pq.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/049\/0\/5713595\/il_570xN.713324809_m2pq.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/049\/0\/5713595\/il_fullxfull.713324809_m2pq.jpg",
      "full_height": 240,
      "full_width": 320
    }, {
      "listing_image_id": 713201642,
      "hex_code": "B08E5F",
      "red": 176,
      "green": 142,
      "blue": 95,
      "hue": 35,
      "saturation": 46,
      "brightness": 69,
      "is_black_and_white": false,
      "creation_tsz": 1421537618,
      "listing_id": 218920194,
      "rank": 2,
      "url_75x75": "https:\/\/img0.etsystatic.com\/050\/0\/5713595\/il_75x75.713201642_ot3v.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/050\/0\/5713595\/il_170x135.713201642_ot3v.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/050\/0\/5713595\/il_570xN.713201642_ot3v.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/050\/0\/5713595\/il_fullxfull.713201642_ot3v.jpg",
      "full_height": 240,
      "full_width": 213
    }, {
      "listing_image_id": 713201742,
      "hex_code": "9E8555",
      "red": 158,
      "green": 133,
      "blue": 85,
      "hue": 39,
      "saturation": 46,
      "brightness": 61,
      "is_black_and_white": false,
      "creation_tsz": 1421537618,
      "listing_id": 218920194,
      "rank": 3,
      "url_75x75": "https:\/\/img0.etsystatic.com\/052\/0\/5713595\/il_75x75.713201742_eu3o.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/052\/0\/5713595\/il_170x135.713201742_eu3o.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/052\/0\/5713595\/il_570xN.713201742_eu3o.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/052\/0\/5713595\/il_fullxfull.713201742_eu3o.jpg",
      "full_height": 240,
      "full_width": 320
    }, {
      "listing_image_id": 713324725,
      "hex_code": "A08766",
      "red": 160,
      "green": 135,
      "blue": 102,
      "hue": 34,
      "saturation": 36,
      "brightness": 62,
      "is_black_and_white": false,
      "creation_tsz": 1421537618,
      "listing_id": 218920194,
      "rank": 4,
      "url_75x75": "https:\/\/img1.etsystatic.com\/055\/0\/5713595\/il_75x75.713324725_2hxr.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/055\/0\/5713595\/il_170x135.713324725_2hxr.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/055\/0\/5713595\/il_570xN.713324725_2hxr.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/055\/0\/5713595\/il_fullxfull.713324725_2hxr.jpg",
      "full_height": 240,
      "full_width": 320
    }],
    "Shop": {
      "shop_id": 5713595,
      "shop_name": "JUSTLOVETOQUILT",
      "user_id": 8504030,
      "creation_tsz": 1258489784,
      "title": "Just Love To Quilt",
      "announcement": null,
      "currency_code": "USD",
      "is_vacation": false,
      "vacation_message": null,
      "sale_message": "Thank you ",
      "digital_sale_message": null,
      "last_updated_tsz": 1421957779,
      "listing_active_count": 12,
      "login_name": "JUSTLOVETOQUILT",
      "accepts_custom_requests": false,
      "policy_welcome": null,
      "policy_payment": null,
      "policy_shipping": null,
      "policy_refunds": null,
      "policy_additional": null,
      "policy_seller_info": null,
      "policy_updated_tsz": 1296841374,
      "vacation_autoreply": null,
      "url": "https:\/\/www.etsy.com\/shop\/JUSTLOVETOQUILT?utm_source=explorer&utm_medium=api&utm_campaign=api",
      "image_url_760x100": "https:\/\/img0.etsystatic.com\/018\/0\/5713595\/iusb_760x100.12218802_gcy4.jpg",
      "num_favorers": 129,
      "languages": ["en-US"],
      "upcoming_local_event_id": null
    }
  }, {
    "listing_id": 215387122,
    "state": "active",
    "user_id": 12501577,
    "category_id": 69171729,
    "title": "Tule Terrain in Cactus, Leah Duncan, Art Gallery Fabrics, 100% Cotton Fabric, TL-30025",
    "description": "Terrain in Cactus from the Tule Collection by Leah Duncan for Art Gallery Fabrics.  This is a quilting weight cotton fabric with a soft feel.\r\n\r\nFat quarters and yardage available.  Please choose desired size and quantity from drop down menu or contact seller for a custom listing.\r\n\r\nFat Quarters measure 18 inches by 21 inches.\r\nHalf Yards measure 18 inches by 44 inches.  \r\n\r\nIf you purchase multiple quantities, I will combine yardage and send fabric as one single piece.\r\n\r\nAdditional yardage often available, contact seller if interested in a larger cut.\r\n\r\n100% cotton fabric, new, unwashed, from a smoke-free and pet-free shop.\r\n\r\nMore from Tule here:\r\nhttps:\/\/www.etsy.com\/shop\/FreshModernFabric\/search?search_query=tule\r\n\r\nMore from Leah Duncan here:\r\nhttps:\/\/www.etsy.com\/shop\/FreshModernFabric\/search?search_query=leah+duncan\r\n\r\nMore from Art Gallery here:\r\nhttps:\/\/www.etsy.com\/shop\/FreshModernFabric\/search?search_query=art+gallery\r\n\r\n*****Please feel free to contact me for a custom listing if you are purchasing multiple items or if you want additional yardage. I can give the lowest possible shipping price for custom listings and am always happy to set up a listing especially for you. I also refund significant shipping overages if you purchase multiple listings and the shipping charges come out too high.*****",
    "creation_tsz": 1421957684,
    "ending_tsz": 1432322084,
    "original_creation_tsz": 1418658650,
    "last_modified_tsz": 1421957684,
    "price": "3.00",
    "currency_code": "USD",
    "quantity": 8,
    "tags": ["art gallery", "leah duncan", "fresh modern fabric", "tule", "nevada sun", "terrain", "cactus", "TL-30025", "TL 30025", "dots", "aqua blue", "mint", "textured solid"],
    "category_path": ["Supplies", "Fabric", "Yardage"],
    "category_path_ids": [69150433, 68888310, 69171729],
    "materials": ["fabric", "cotton"],
    "shop_section_id": 7962800,
    "featured_rank": null,
    "state_tsz": 1418658650,
    "url": "https:\/\/www.etsy.com\/listing\/215387122\/tule-terrain-in-cactus-leah-duncan-art?utm_source=explorer&utm_medium=api&utm_campaign=api",
    "views": 37,
    "num_favorers": 6,
    "shipping_template_id": 10095647,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "someone_else",
    "is_supply": "true",
    "when_made": "2010_2015",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": true,
    "used_manufacturer": false,
    "Images": [{
      "listing_image_id": 699714037,
      "hex_code": "CEE4D7",
      "red": 206,
      "green": 228,
      "blue": 215,
      "hue": 145,
      "saturation": 9,
      "brightness": 89,
      "is_black_and_white": false,
      "creation_tsz": 1418658650,
      "listing_id": 215387122,
      "rank": 1,
      "url_75x75": "https:\/\/img1.etsystatic.com\/055\/0\/6211819\/il_75x75.699714037_foe2.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/055\/0\/6211819\/il_170x135.699714037_foe2.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/055\/0\/6211819\/il_570xN.699714037_foe2.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/055\/0\/6211819\/il_fullxfull.699714037_foe2.jpg",
      "full_height": 500,
      "full_width": 500
    }, {
      "listing_image_id": 699709779,
      "hex_code": "B59F92",
      "red": 181,
      "green": 159,
      "blue": 146,
      "hue": 22,
      "saturation": 19,
      "brightness": 70,
      "is_black_and_white": false,
      "creation_tsz": 1418658650,
      "listing_id": 215387122,
      "rank": 2,
      "url_75x75": "https:\/\/img1.etsystatic.com\/054\/0\/6211819\/il_75x75.699709779_3ysp.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/054\/0\/6211819\/il_170x135.699709779_3ysp.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/054\/0\/6211819\/il_570xN.699709779_3ysp.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/054\/0\/6211819\/il_fullxfull.699709779_3ysp.jpg",
      "full_height": 667,
      "full_width": 1000
    }, {
      "listing_image_id": 699590610,
      "hex_code": "B39F96",
      "red": 179,
      "green": 159,
      "blue": 150,
      "hue": 19,
      "saturation": 16,
      "brightness": 70,
      "is_black_and_white": false,
      "creation_tsz": 1418658650,
      "listing_id": 215387122,
      "rank": 3,
      "url_75x75": "https:\/\/img0.etsystatic.com\/054\/0\/6211819\/il_75x75.699590610_r55s.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/054\/0\/6211819\/il_170x135.699590610_r55s.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/054\/0\/6211819\/il_570xN.699590610_r55s.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/054\/0\/6211819\/il_fullxfull.699590610_r55s.jpg",
      "full_height": 667,
      "full_width": 1000
    }],
    "Shop": {
      "shop_id": 6211819,
      "shop_name": "FreshModernFabric",
      "user_id": 12501577,
      "creation_tsz": 1297273255,
      "title": "Designer Prints and Modern Basics",
      "announcement": "Please feel free to contact me for a custom order if you are purchasing multiple items or if you want additional yardage. I can give the lowest possible shipping price for custom orders and am always happy to set up an order especially for you. I also refund significant shipping overages if you purchase multiple listings and the shipping charges come out too high.\r\n\r\nIf you would like to keep updated on shop announcements and new fabrics, either &quot;like&quot; FRESH MODERN FABRIC on Facebook or send an email to freshmodernfabric[AT]gmail.com to be placed on the mailing list.  (I will NEVER share or use your email address for other purposes.)",
      "currency_code": "USD",
      "is_vacation": false,
      "vacation_message": "FRESH MODERN FABRIC will be back on Monday, May 19th, 2014.  I will still be available through Etsy messages and emails if you need to reach me but my response time may be delayed.  Thanks for visiting and please come back to shop when I re-open on May 19th.\r\n",
      "sale_message": "Thank you for purchasing fabric from Fresh Modern Fabric!  I very much appreciate your business.\r\n\r\nIf you would like to keep updated on shop announcements and new fabrics, either &quot;like&quot; FRESH MODERN FABRIC on Facebook or send an email to freshmodernfabric[AT]gmail.com to be placed on the mailing list.  (I will NEVER share or use your email address for other purposes.)\r\n\r\n***INTERNATIONAL CUSTOMERS PLEASE TAKE NOTE***\r\nI cannot be responsible for items lost in the mail.  I try to keep shipping costs down by using first class and priority mail shipping to International addresses.  Unfortunately, these shipping methods do not include shipment tracking and delivery confirmation services to international addresses.  In order to provide these track and confirm services, I need to send your order by registered mail, which I am happy to do at an extra cost.  Please contact me and ask for registered mail shipping if you want protection for items lost in the mail, as I will not otherwise offer refunds or replacements for items lost in the mail.  No exceptions!\r\n\r\nThanks,\r\nAlice",
      "digital_sale_message": null,
      "last_updated_tsz": 1421957686,
      "listing_active_count": 1382,
      "login_name": "FreshModernFabric",
      "accepts_custom_requests": true,
      "policy_welcome": "Welcome to Fresh Modern Fabric!\r\n\r\nFabric shopping makes me really, truly happy.  I strive to make shopping at Fresh Modern Fabric equally joyful for you by offering amazing customer service, competitive pricing, an outstanding selection of designer fabrics and lightning fast shipping.\r\n\r\nI am always happy to set up a custom listing for you with different fabric quantities or individualized combinations of any of the products I carry...just contact me through the link on the left sidebar!",
      "policy_payment": "I accept PayPal for payment.  You can pay by credit card with PayPal and you do not even need to set up a PayPal account.\r\n\r\nAn Ohio state sales tax of 6.5% will be charged to all orders shipped to an Ohio address.",
      "policy_shipping": "I will happily combine shipping and I also refund significant shipping overcharges.  If you need any special shipping options, such as expedited shipping, registered mail, insurance or anything else, please contact me before purchasing so that I can make the necessary adjustments to your order.\r\n\r\nI ship through USPS and I ship fast!  I am located right across the street from the post office and make multiple trips there a day.\r\n\r\n***INTERNATIONAL CUSTOMERS PLEASE TAKE NOTE***\r\n\r\nCustoms forms will always state the full amount paid for the merchandise (not including shipping charges). Customs duties may apply upon receipt and are the responsibility of the customer. Customs taxes and rules vary by location, so please consult your local jurisdiction for more information on additional customs taxes that may apply.\r\n\r\nI cannot be responsible for items lost in the mail.  I try to keep shipping costs down by using first class and priority mail shipping to International addresses.  Unfortunately, these shipping methods do not include shipment tracking and delivery confirmation services to international addresses.  In order to provide these track and confirm services, I need to send your order by registered mail, which I am happy to do at an extra cost.  Please ask me to add registered mail shipping to your order if you want protection for items lost in the mail, as I will not otherwise offer refunds or replacements for items lost in the mail.  No exceptions!",
      "policy_refunds": "I know it can often be difficult to buy fabric online.  The last thing I want is for you to be dissatisified with your purchase once it arrives on your doorstep!  If you are unhappy with your fabric for any reason, please contact me right away.  I will happily replace damaged or flawed fabrics.  While I cannot offer refunds on cut to order fabrics, I am willing to offer an exchange on regularly priced fabrics within 14 days of purchase.  I cannot exchange or refund sale fabrics.  The customer is responsible for original and return shipping costs for exchanges, unless I am at fault for sending the wrong item.",
      "policy_additional": null,
      "policy_seller_info": null,
      "policy_updated_tsz": 1385236091,
      "vacation_autoreply": "FRESH MODERN FABRIC  is closed until Monday, May 19th, 2014.  I&#39;m still checking messages and emails, however, so will try to get back to you as soon as possible.\r\n\r\nThanks!\r\nAlice",
      "url": "https:\/\/www.etsy.com\/shop\/FreshModernFabric?utm_source=explorer&utm_medium=api&utm_campaign=api",
      "image_url_760x100": "https:\/\/img0.etsystatic.com\/050\/0\/6211819\/iusb_760x100.14678346_sg1w.jpg",
      "num_favorers": 8607,
      "languages": ["en-US"],
      "upcoming_local_event_id": null
    }
  }, {
    "listing_id": 219590586,
    "state": "active",
    "user_id": 5432958,
    "category_id": 68910294,
    "title": "Sashiko Southwest Cactus Blooming pre-printed wash out navy blue Kona cotton fabric",
    "description": "Sashiko Southwest designs are created by artist Joyce Martin Perz of Albuquerque, New Mexico. Using traditional Native American motifs and cactus as inspiration, she has printed these sashiko fabrics with easy to follow lines that wash out after you&#39;ve completed the design. Made in the USA. \n\nFabric measures 14&quot; x 14&quot;. \n\n",
    "creation_tsz": 1421957668,
    "ending_tsz": 1432322068,
    "original_creation_tsz": 1421957606,
    "last_modified_tsz": 1421957668,
    "price": "10.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["blooming cactus", "cactus blooming", "kona cotton", "indigo blue", "Native American", "sashiko southwest", "quilting", "sashiko", "oriental", "asian", "cotton", "blue"],
    "category_path": ["Supplies", "Pattern", "Sewing"],
    "category_path_ids": [69150433, 69150513, 68910294],
    "materials": ["fabric", "cotton"],
    "shop_section_id": 5363996,
    "featured_rank": null,
    "state_tsz": 1421957606,
    "url": "https:\/\/www.etsy.com\/listing\/219590586\/sashiko-southwest-cactus-blooming-pre?utm_source=explorer&utm_medium=api&utm_campaign=api",
    "views": 0,
    "num_favorers": 0,
    "shipping_template_id": null,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "someone_else",
    "is_supply": "true",
    "when_made": "2010_2015",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false,
    "Images": [{
      "listing_image_id": 715763442,
      "hex_code": "515D6F",
      "red": 81,
      "green": 93,
      "blue": 111,
      "hue": 216,
      "saturation": 27,
      "brightness": 43,
      "is_black_and_white": false,
      "creation_tsz": 1421957668,
      "listing_id": 219590586,
      "rank": 1,
      "url_75x75": "https:\/\/img0.etsystatic.com\/054\/0\/5219429\/il_75x75.715763442_ggrn.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/054\/0\/5219429\/il_170x135.715763442_ggrn.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/054\/0\/5219429\/il_570xN.715763442_ggrn.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/054\/0\/5219429\/il_fullxfull.715763442_ggrn.jpg",
      "full_height": 1500,
      "full_width": 1500
    }],
    "Shop": {
      "shop_id": 5219429,
      "shop_name": "kimonomomo",
      "user_id": 5432958,
      "creation_tsz": 1196359191,
      "title": "KimonoMomo ~ Exquisite Japanese Textiles ~ \u304d\u3082\u306e\u6843",
      "announcement": "New and vintage fabrics arriving every week. Listings updated almost every day! Specializing in new and vintage Japanese textiles, sashiko supplies, kimono, books, and other arts since 2005. Kona Bay, Alexander Henry, Olympus, Hida, QH Textiles, TransPacific, etc. \r\n\r\nIf it looks like I&#39;m sold out of something you want, ASK! I might have more available. \r\n\r\n**INTERNATIONAL BUYERS PLEASE READ** I cannot be held responsible for your package once it leaves the USA. Shipping insurance is required and included on all orders over $20 except countries not covered by my insurer. \r\n\r\nCalifornia buyers will be charged sales tax.\r\n\r\nProblem with your order? CONTACT ME. I&#39;ll be happy to fix it. ",
      "currency_code": "USD",
      "is_vacation": false,
      "vacation_message": "Sunday October 20 the shop will be live at the Mini Maker Fair in Oakland, California. Back on Monday! http:\/\/ebmakerfaire.wordpress.com\/2013makers\/\r\n\r\nYou can also find me on Facebook (KimonoMomo) or Twitter (@kimonomomo).",
      "sale_message": "Thank you for your purchase. Please contact me if you have and special needs or if this is for a gift. Your package will ship via USPS first class mail. Domestic packages over 13 ounces ship via Priority Mail. Insurance is included in packages over $50. \r\n\r\nINTERNATIONAL BUYERS: I cannot be held responsible for your package once it leaves the USA. Insurance is included in your shipping fee, but it may take 45-120 days to file a claim, depending on where you live. YOUR COUNTRY MAY CHARGE IMPORT DUTY TAXES. I have no control over this.\r\n\r\nIF YOU NEED THIS FOR IMMEDIATE DELIVERY LET ME KNOW! Most items ship within 24-48 hours, but not always, especially over weekends. If you have a special event (birthday, wedding, etc.) and need your item RIGHT NOW, YOU MUST TELL ME AT THE TIME OF YOUR ORDER. I have no control over the United States Postal Service. If I ship within my listed 3 days and it arrives later than you want, there&#39;s nothing I can do, especially for international orders. \r\n\r\n\r\n",
      "digital_sale_message": null,
      "last_updated_tsz": 1421923960,
      "listing_active_count": 436,
      "login_name": "kimonomomo",
      "accepts_custom_requests": true,
      "policy_welcome": "At KimonoMomo I want you to be happy with your purchase. Since 2005 I have built up a solid base of repeat customers on Etsy who enjoy using unusual fabrics and materials in their creations and appreciate good customer service. It would make me happy for you to be one of them!",
      "policy_payment": "Paypal is preferred, but I also accept checks & money orders (US only). Please make your payment within 3 days. If you are unable to pay within 3 days, contact me and let me know. ",
      "policy_shipping": "All orders ship within 4 business days. Most orders are shipped in a plastic bag inside a Tyvek (water and tear resistant) envelope. Orders weighing 13 ounces or more will be shipped via Priority Mail within the US. \n\nInsurance is available for packages shipped within the US and some foreign countries. Domestic insurance is carried by USPS, foreign insurance is by U-pic. ",
      "policy_refunds": "If you are not satisfied with your purchase, please contact me to discuss options. Return shipping is the responsibility of the buyer. I offer insurance for items lost in the mail or damaged in transit. \n\n***If you do not contact me prior to shipment and do not purchase insurance, I cannot be held responsible for your package.*** ",
      "policy_additional": "Custom orders are always welcome. Feel free to contact me with your ideas or requests. ",
      "policy_seller_info": null,
      "policy_updated_tsz": 1371654945,
      "vacation_autoreply": "Hi there! This is just a pesky auto-reply. I&#39;m not here. \r\n\r\nYou can reach me directly at [kimonomomo at gmail dot com] and I will get back to you.",
      "url": "https:\/\/www.etsy.com\/shop\/kimonomomo?utm_source=explorer&utm_medium=api&utm_campaign=api",
      "image_url_760x100": "https:\/\/img1.etsystatic.com\/020\/0\/5219429\/iusb_760x100.12453319_gs6j.jpg",
      "num_favorers": 4681,
      "languages": ["en-US"],
      "upcoming_local_event_id": null
    }
  }, {
    "listing_id": 219590203,
    "state": "active",
    "user_id": 5432958,
    "category_id": 68910294,
    "title": "Sashiko Southwest Protecting Beauty pre-printed wash out navy blue Kona cotton fabric",
    "description": "Sashiko Southwest designs are created by artist Joyce Martin Perz of Albuquerque, New Mexico. Using traditional Native American motifs and cactus as inspiration, she has printed these sashiko fabrics with easy to follow lines that wash out after you&#39;ve completed the design. Made in the USA. \n\nFabric measures 14&quot; x 14&quot;. \n\nSecond photo shows a completed project. This listing is for the fabric only, thread and needles are available separately. ",
    "creation_tsz": 1421957565,
    "ending_tsz": 1432321965,
    "original_creation_tsz": 1421957473,
    "last_modified_tsz": 1421957565,
    "price": "10.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["flower", "protecting beauty", "cactus", "kona cotton", "indigo blue", "Native American", "sashiko southwest", "quilting", "sashiko", "oriental", "asian", "cotton", "blue"],
    "category_path": ["Supplies", "Pattern", "Sewing"],
    "category_path_ids": [69150433, 69150513, 68910294],
    "materials": ["fabric", "cotton"],
    "shop_section_id": 5363996,
    "featured_rank": null,
    "state_tsz": 1421957474,
    "url": "https:\/\/www.etsy.com\/listing\/219590203\/sashiko-southwest-protecting-beauty-pre?utm_source=explorer&utm_medium=api&utm_campaign=api",
    "views": 0,
    "num_favorers": 0,
    "shipping_template_id": null,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "someone_else",
    "is_supply": "true",
    "when_made": "2010_2015",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false,
    "Images": [{
      "listing_image_id": 715885561,
      "hex_code": "505C6C",
      "red": 80,
      "green": 92,
      "blue": 108,
      "hue": 214,
      "saturation": 25,
      "brightness": 42,
      "is_black_and_white": false,
      "creation_tsz": 1421957564,
      "listing_id": 219590203,
      "rank": 1,
      "url_75x75": "https:\/\/img1.etsystatic.com\/057\/0\/5219429\/il_75x75.715885561_tkyg.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/057\/0\/5219429\/il_170x135.715885561_tkyg.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/057\/0\/5219429\/il_570xN.715885561_tkyg.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/057\/0\/5219429\/il_fullxfull.715885561_tkyg.jpg",
      "full_height": 1500,
      "full_width": 1500
    }, {
      "listing_image_id": 715762304,
      "hex_code": "7B7C77",
      "red": 123,
      "green": 124,
      "blue": 119,
      "hue": 72,
      "saturation": 4,
      "brightness": 48,
      "is_black_and_white": false,
      "creation_tsz": 1421957565,
      "listing_id": 219590203,
      "rank": 2,
      "url_75x75": "https:\/\/img0.etsystatic.com\/045\/0\/5219429\/il_75x75.715762304_cg1o.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/045\/0\/5219429\/il_170x135.715762304_cg1o.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/045\/0\/5219429\/il_570xN.715762304_cg1o.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/045\/0\/5219429\/il_fullxfull.715762304_cg1o.jpg",
      "full_height": 1500,
      "full_width": 1500
    }],
    "Shop": {
      "shop_id": 5219429,
      "shop_name": "kimonomomo",
      "user_id": 5432958,
      "creation_tsz": 1196359191,
      "title": "KimonoMomo ~ Exquisite Japanese Textiles ~ \u304d\u3082\u306e\u6843",
      "announcement": "New and vintage fabrics arriving every week. Listings updated almost every day! Specializing in new and vintage Japanese textiles, sashiko supplies, kimono, books, and other arts since 2005. Kona Bay, Alexander Henry, Olympus, Hida, QH Textiles, TransPacific, etc. \r\n\r\nIf it looks like I&#39;m sold out of something you want, ASK! I might have more available. \r\n\r\n**INTERNATIONAL BUYERS PLEASE READ** I cannot be held responsible for your package once it leaves the USA. Shipping insurance is required and included on all orders over $20 except countries not covered by my insurer. \r\n\r\nCalifornia buyers will be charged sales tax.\r\n\r\nProblem with your order? CONTACT ME. I&#39;ll be happy to fix it. ",
      "currency_code": "USD",
      "is_vacation": false,
      "vacation_message": "Sunday October 20 the shop will be live at the Mini Maker Fair in Oakland, California. Back on Monday! http:\/\/ebmakerfaire.wordpress.com\/2013makers\/\r\n\r\nYou can also find me on Facebook (KimonoMomo) or Twitter (@kimonomomo).",
      "sale_message": "Thank you for your purchase. Please contact me if you have and special needs or if this is for a gift. Your package will ship via USPS first class mail. Domestic packages over 13 ounces ship via Priority Mail. Insurance is included in packages over $50. \r\n\r\nINTERNATIONAL BUYERS: I cannot be held responsible for your package once it leaves the USA. Insurance is included in your shipping fee, but it may take 45-120 days to file a claim, depending on where you live. YOUR COUNTRY MAY CHARGE IMPORT DUTY TAXES. I have no control over this.\r\n\r\nIF YOU NEED THIS FOR IMMEDIATE DELIVERY LET ME KNOW! Most items ship within 24-48 hours, but not always, especially over weekends. If you have a special event (birthday, wedding, etc.) and need your item RIGHT NOW, YOU MUST TELL ME AT THE TIME OF YOUR ORDER. I have no control over the United States Postal Service. If I ship within my listed 3 days and it arrives later than you want, there&#39;s nothing I can do, especially for international orders. \r\n\r\n\r\n",
      "digital_sale_message": null,
      "last_updated_tsz": 1421923960,
      "listing_active_count": 436,
      "login_name": "kimonomomo",
      "accepts_custom_requests": true,
      "policy_welcome": "At KimonoMomo I want you to be happy with your purchase. Since 2005 I have built up a solid base of repeat customers on Etsy who enjoy using unusual fabrics and materials in their creations and appreciate good customer service. It would make me happy for you to be one of them!",
      "policy_payment": "Paypal is preferred, but I also accept checks & money orders (US only). Please make your payment within 3 days. If you are unable to pay within 3 days, contact me and let me know. ",
      "policy_shipping": "All orders ship within 4 business days. Most orders are shipped in a plastic bag inside a Tyvek (water and tear resistant) envelope. Orders weighing 13 ounces or more will be shipped via Priority Mail within the US. \n\nInsurance is available for packages shipped within the US and some foreign countries. Domestic insurance is carried by USPS, foreign insurance is by U-pic. ",
      "policy_refunds": "If you are not satisfied with your purchase, please contact me to discuss options. Return shipping is the responsibility of the buyer. I offer insurance for items lost in the mail or damaged in transit. \n\n***If you do not contact me prior to shipment and do not purchase insurance, I cannot be held responsible for your package.*** ",
      "policy_additional": "Custom orders are always welcome. Feel free to contact me with your ideas or requests. ",
      "policy_seller_info": null,
      "policy_updated_tsz": 1371654945,
      "vacation_autoreply": "Hi there! This is just a pesky auto-reply. I&#39;m not here. \r\n\r\nYou can reach me directly at [kimonomomo at gmail dot com] and I will get back to you.",
      "url": "https:\/\/www.etsy.com\/shop\/kimonomomo?utm_source=explorer&utm_medium=api&utm_campaign=api",
      "image_url_760x100": "https:\/\/img1.etsystatic.com\/020\/0\/5219429\/iusb_760x100.12453319_gs6j.jpg",
      "num_favorers": 4681,
      "languages": ["en-US"],
      "upcoming_local_event_id": null
    }
  }, {
    "listing_id": 219590418,
    "state": "active",
    "user_id": 6846562,
    "category_id": 69176399,
    "title": "Drake - Tiny Single Succulent Terrarium desktop Arrangement ",
    "description": "A tiny succulent arrangement made up of one cute succulent and colored moss, arranged in open-top glass candleholder. Its about 3ish inches tall; My hand is included in the picture for size reference. \n\nYou get the exact one pictured, it comes pre-made and arranged.\n\nCarefully packaged and shipped to ensure safe delivery. C: if you are local to me and would like to just pick it up in person it can be arranged. \n\nWill include basic care instructions.\n\nMakes a cute gift! \n\nMessage me with any questions or concerns!  \n\nIf you live outside of the U.S., message me and I can give you accurate shipping rates! ",
    "creation_tsz": 1421957537,
    "ending_tsz": 1432321937,
    "original_creation_tsz": 1421957537,
    "last_modified_tsz": 1421957540,
    "price": "15.00",
    "currency_code": "USD",
    "quantity": 1,
    "tags": ["arrangement", "natural", "cactus", "flowers", "garden", "glass", "moss", "succulents", "terrarium", "desert", "plant", "succulent", "ooak"],
    "category_path": ["Plants and Edibles", "Plant", "Terrarium"],
    "category_path_ids": [68887346, 69153219, 69176399],
    "materials": ["Carbon", "gravel", "activated charcoal", "pebbles", "soil", "succulent", "moss", "glass", "jar", "rocks", "sphagnum moss", "reindeer moss"],
    "shop_section_id": 16278529,
    "featured_rank": null,
    "state_tsz": 1421957537,
    "url": "https:\/\/www.etsy.com\/listing\/219590418\/drake-tiny-single-succulent-terrarium?utm_source=explorer&utm_medium=api&utm_campaign=api",
    "views": 0,
    "num_favorers": 0,
    "shipping_template_id": 6794990730,
    "processing_min": 3,
    "processing_max": 5,
    "who_made": "collective",
    "is_supply": "false",
    "when_made": "2010_2015",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": null,
    "non_taxable": false,
    "is_customizable": false,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": false,
    "used_manufacturer": false,
    "Images": [{
      "listing_image_id": 715761926,
      "hex_code": "8C7D69",
      "red": 140,
      "green": 125,
      "blue": 105,
      "hue": 34,
      "saturation": 25,
      "brightness": 54,
      "is_black_and_white": false,
      "creation_tsz": 1421957537,
      "listing_id": 219590418,
      "rank": 1,
      "url_75x75": "https:\/\/img0.etsystatic.com\/048\/0\/9775684\/il_75x75.715761926_l7mf.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/048\/0\/9775684\/il_170x135.715761926_l7mf.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/048\/0\/9775684\/il_570xN.715761926_l7mf.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/048\/0\/9775684\/il_fullxfull.715761926_l7mf.jpg",
      "full_height": 905,
      "full_width": 818
    }, {
      "listing_image_id": 715761928,
      "hex_code": "80776F",
      "red": 128,
      "green": 119,
      "blue": 111,
      "hue": 28,
      "saturation": 13,
      "brightness": 50,
      "is_black_and_white": false,
      "creation_tsz": 1421957537,
      "listing_id": 219590418,
      "rank": 2,
      "url_75x75": "https:\/\/img0.etsystatic.com\/049\/0\/9775684\/il_75x75.715761928_4ur3.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/049\/0\/9775684\/il_170x135.715761928_4ur3.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/049\/0\/9775684\/il_570xN.715761928_4ur3.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/049\/0\/9775684\/il_fullxfull.715761928_4ur3.jpg",
      "full_height": 1500,
      "full_width": 1125
    }, {
      "listing_image_id": 715761930,
      "hex_code": "928E80",
      "red": 146,
      "green": 142,
      "blue": 128,
      "hue": 47,
      "saturation": 12,
      "brightness": 57,
      "is_black_and_white": false,
      "creation_tsz": 1421957537,
      "listing_id": 219590418,
      "rank": 3,
      "url_75x75": "https:\/\/img0.etsystatic.com\/050\/0\/9775684\/il_75x75.715761930_2okv.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/050\/0\/9775684\/il_170x135.715761930_2okv.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/050\/0\/9775684\/il_570xN.715761930_2okv.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/050\/0\/9775684\/il_fullxfull.715761930_2okv.jpg",
      "full_height": 1500,
      "full_width": 1125
    }, {
      "listing_image_id": 715761934,
      "hex_code": "938F7E",
      "red": 147,
      "green": 143,
      "blue": 126,
      "hue": 49,
      "saturation": 14,
      "brightness": 57,
      "is_black_and_white": false,
      "creation_tsz": 1421957537,
      "listing_id": 219590418,
      "rank": 4,
      "url_75x75": "https:\/\/img0.etsystatic.com\/052\/0\/9775684\/il_75x75.715761934_c1p8.jpg",
      "url_170x135": "https:\/\/img0.etsystatic.com\/052\/0\/9775684\/il_170x135.715761934_c1p8.jpg",
      "url_570xN": "https:\/\/img0.etsystatic.com\/052\/0\/9775684\/il_570xN.715761934_c1p8.jpg",
      "url_fullxfull": "https:\/\/img0.etsystatic.com\/052\/0\/9775684\/il_fullxfull.715761934_c1p8.jpg",
      "full_height": 1500,
      "full_width": 1125
    }],
    "Shop": {
      "shop_id": 9775684,
      "shop_name": "AllieCatsTrinkets",
      "user_id": 6846562,
      "creation_tsz": 1406063428,
      "title": null,
      "announcement": "Hello! I will be listing new Terrariums this week. My cat decided to knock down a handful of my terrariums and now I have to recreate and try to salvage what can be recovered from the wreckage. \n\nKeep an eye out! Thank you for looking!\n\nKeep in mind I can still make custom orders! C: ",
      "currency_code": "USD",
      "is_vacation": false,
      "vacation_message": null,
      "sale_message": null,
      "digital_sale_message": null,
      "last_updated_tsz": 1417384878,
      "listing_active_count": 9,
      "login_name": "Madefrcupcakeicing",
      "accepts_custom_requests": false,
      "policy_welcome": null,
      "policy_payment": null,
      "policy_shipping": null,
      "policy_refunds": null,
      "policy_additional": null,
      "policy_seller_info": null,
      "policy_updated_tsz": 1418658394,
      "vacation_autoreply": null,
      "url": "https:\/\/www.etsy.com\/shop\/AllieCatsTrinkets?utm_source=explorer&utm_medium=api&utm_campaign=api",
      "image_url_760x100": "https:\/\/img0.etsystatic.com\/056\/0\/9775684\/iusb_760x100.14614518_maj5.jpg",
      "num_favorers": 15,
      "languages": ["en-US"],
      "upcoming_local_event_id": null
    }
  }, {
    "listing_id": 100104457,
    "state": "active",
    "user_id": 19956377,
    "category_id": 69172099,
    "title": "Denyse Schmidt&#39;s Hope Valley Fabric in Cactus Calico Fiesta 1 yard",
    "description": "quality quilters cotton\r\norange, cream, black\r\nsmoke free studio\r\nquick shipping",
    "creation_tsz": 1421957404,
    "ending_tsz": 1432321804,
    "original_creation_tsz": 1337346950,
    "last_modified_tsz": 1421957404,
    "price": "8.00",
    "currency_code": "USD",
    "quantity": 2,
    "tags": ["denyse schmidt", "hope valley", "calico cactus", "orange", "cream", "black", "grid", "quilting cotton"],
    "category_path": ["Supplies", "Fabric", "Cotton"],
    "category_path_ids": [69150433, 68888310, 69172099],
    "materials": ["cotton"],
    "shop_section_id": 11381717,
    "featured_rank": null,
    "state_tsz": 1421878868,
    "url": "https:\/\/www.etsy.com\/listing\/100104457\/denyse-schmidts-hope-valley-fabric-in?utm_source=explorer&utm_medium=api&utm_campaign=api",
    "views": 206,
    "num_favorers": 16,
    "shipping_template_id": 162168140,
    "processing_min": 1,
    "processing_max": 1,
    "who_made": "someone_else",
    "is_supply": "true",
    "when_made": "2010_2015",
    "is_private": false,
    "recipient": null,
    "occasion": null,
    "style": ["Cottage Chic"],
    "non_taxable": false,
    "is_customizable": true,
    "is_digital": false,
    "file_data": "",
    "language": "en-US",
    "has_variations": true,
    "used_manufacturer": false,
    "Images": [{
      "listing_image_id": 544210961,
      "hex_code": "C67B50",
      "red": 198,
      "green": 123,
      "blue": 80,
      "hue": 22,
      "saturation": 59,
      "brightness": 77,
      "is_black_and_white": false,
      "creation_tsz": 1388270695,
      "listing_id": 100104457,
      "rank": 1,
      "url_75x75": "https:\/\/img1.etsystatic.com\/041\/0\/6787766\/il_75x75.544210961_s1tg.jpg",
      "url_170x135": "https:\/\/img1.etsystatic.com\/041\/0\/6787766\/il_170x135.544210961_s1tg.jpg",
      "url_570xN": "https:\/\/img1.etsystatic.com\/041\/0\/6787766\/il_570xN.544210961_s1tg.jpg",
      "url_fullxfull": "https:\/\/img1.etsystatic.com\/041\/0\/6787766\/il_fullxfull.544210961_s1tg.jpg",
      "full_height": 299,
      "full_width": 290
    }],
    "Shop": {
      "shop_id": 6787766,
      "shop_name": "karensstash",
      "user_id": 19956377,
      "creation_tsz": 1330551637,
      "title": "Karen&#39;s Stash",
      "announcement": " In this shop, I sell fabric, patterns, quilt kits and other supplies for making quilts.  I specialize in Sweetwater fabrics and patterns.  Other shop: http:\/\/www.quiltedbykaren.etsy.com ",
      "currency_code": "USD",
      "is_vacation": false,
      "vacation_message": null,
      "sale_message": "Thank you so much for buying supplies from Karen&#39;s Stash.  Let me know if you have questions or concerns.",
      "digital_sale_message": "Your pdf pattern will be available to you as a download as soon as you buy the pattern.  Contact me with any questions about the directions.",
      "last_updated_tsz": 1421787686,
      "listing_active_count": 490,
      "login_name": "brauerkaren",
      "accepts_custom_requests": true,
      "policy_welcome": "Hi and welcome to Karen&#39;s Stash.  I sell fabrics, patterns, kits and other supplies for making quilts.  Enjoy your visit.",
      "policy_payment": "Payment must be within 3 days using paypal or within a week if sending a check or money order.  Customer is responsible for duties and customs fees.  I WILL NOT UNDERVALUE AN ITEM ON THE CUSTOMS FORMS IN ORDER TO REDUCE YOUR CUSTOMS PAYMENT.  PLEASE DO NOT ASK ME TO DO THIS.",
      "policy_shipping": "I use the United States Postal Service.  I send the cheapest way unless I have promised delivery by a certain date.  Usually I will send by Priority mail.  I refund any amount of shipping overage that is $2 over what you paid for shipping.",
      "policy_refunds": "No refund on already cut fabric unless I have made a mistake on the order.  You may return it for a trade.  On other items, full refund of amount paid less the Etsy fees for items returned to me within 10 days. I do NOT pay return postage.  ",
      "policy_additional": "I give fabric and quilts to the following charities:, Quilts for Kids,  Ronald McDonald House  (million pillow case challenge) and occasionally I donate a quilt for a silent auction to benefit a local charity or cause.",
      "policy_seller_info": "Karen Brauer\r\n335 Antelope Dr. W.\r\nBennett, CO 80102\r\nUSA\r\n303-644-5681\r\n",
      "policy_updated_tsz": 1417743257,
      "vacation_autoreply": null,
      "url": "https:\/\/www.etsy.com\/shop\/karensstash?utm_source=explorer&utm_medium=api&utm_campaign=api",
      "image_url_760x100": "https:\/\/img0.etsystatic.com\/006\/0\/6787766\/iusb_760x100.9883968_768n.jpg",
      "num_favorers": 321,
      "languages": ["en-US"],
      "upcoming_local_event_id": null
    }
  }],
  "params": {
    "limit": "9",
    "offset": 0,
    "page": null,
    "keywords": "cactus",
    "sort_on": "created",
    "sort_order": "down",
    "min_price": null,
    "max_price": null,
    "color": null,
    "color_accuracy": 0,
    "tags": null,
    "category": null,
    "location": null,
    "lat": null,
    "lon": null,
    "region": null,
    "geo_level": "city",
    "accepts_gift_cards": "false",
    "translate_keywords": "false"
  },
  "type": "Listing",
  "pagination": {
    "effective_limit": 9,
    "effective_offset": 0,
    "next_offset": 9,
    "effective_page": 1,
    "next_page": 2
  }
};
